# Generated by Django 4.1.6 on 2023-02-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('com_name', models.CharField(max_length=20)),
                ('expiration_data', models.DateField()),
                ('masked_number', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('users', models.JSONField()),
                ('cards', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('com_name', models.CharField(max_length=20)),
                ('user_cards', models.JSONField()),
                ('user_permission', models.CharField(max_length=10)),
            ],
        ),
    ]
