# Generated by Django 4.1.6 on 2023-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cards',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.JSONField(default=list),
        ),
    ]
